version: "2"
services:
  db:
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    networks:
      network:
        ipv4_address: 172.130.0.2
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    networks:
      network:
        ipv4_address: 172.130.0.3
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    restart: always
  node_pfj:
    depends_on:
      - wordpress
    image: node:8
    volumes:
      - .:/opt/example
      - web_cache:/var/cache/nginx
    networks:
      network:
        ipv4_address: 172.130.0.4
    environment:
      WORDPRESS_HOST: http://wordpress
      NGINX_HOST: http://nginx
      NGINX_CACHE: /var/cache/nginx/data_pfj
      EXTERNAL_HOST: http://pfj.trambar.io
    command: [ node, /opt/example/server/index.js ]
    restart: always
  node_et:
    image: node:8
    volumes:
      - .:/opt/example
      - web_cache:/var/cache/nginx
    networks:
      network:
        ipv4_address: 172.130.0.5
    environment:
      WORDPRESS_HOST: https://www.extremetech.com
      NGINX_HOST: http://nginx
      NGINX_CACHE: /var/cache/nginx/data_et
      EXTERNAL_HOST: http://et.trambar.io
    command: [ node, /opt/example/server/index.js ]
    restart: always
  node_rwt:
    image: node:8
    volumes:
      - .:/opt/example
      - web_cache:/var/cache/nginx
    networks:
      network:
        ipv4_address: 172.130.0.6
    environment:
      WORDPRESS_HOST: https://realworldtech.com
      NGINX_HOST: http://nginx
      NGINX_CACHE: /var/cache/nginx/data_rwt
      EXTERNAL_HOST: http://rwt.trambar.io
    command: [ node, /opt/example/server/index.js ]
    restart: always
  nginx:
    depends_on:
      - wordpress
      - node_pfj
      - node_et
      - node_rwt
    image: nginx:latest
    volumes:
      - ./server/nginx:/etc/nginx/conf.d
      - web_cache:/var/cache/nginx
    networks:
      network:
        ipv4_address: 172.130.0.10
    ports:
      - 80:80
    restart: always
volumes:
  db_data:
  web_cache:
networks:
  network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.130.0.0/16
         gateway: 172.130.0.1
