version: "2"
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    restart: always
  node:
    image: node:8
    ports:
      - 8080:80
    volumes:
      - ..:/opt/example
      - ./cache:/var/cache/nginx
    command: [ node, /opt/example/server/index.js ]
    environment:
      WORDPRESS_HOST: wordpress
      NGINX_HOST: nginx
      NGINX_CACHE: /var/cache/nginx/data
    restart: always
  nginx:
    depends_on:
      - wordpress
      - node
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./cache:/var/cache/nginx
    ports:
      - "8000:80"
    restart: always
volumes:
    db_data:
